[package]
name = "perfectengine"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
async-std = { version = "1.13.0", features = ["attributes", "unstable"] }
bytemuck = "1.18.0"
image = "0.25.2"
mshio = "0.4.2"
sdl2 = { version = "0.37.0", features = ["raw-window-handle"] }
wgpu = "22.1.0"
